# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_del_clt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 300)
        Dialog.setMinimumSize(QtCore.QSize(650, 300))
        Dialog.setMaximumSize(QtCore.QSize(650, 300))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 20, 123, 18))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 601, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setContentsMargins(20, 20, 20, 0)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.dSignationLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dSignationLabel.setObjectName("dSignationLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dSignationLabel)
        self.identifiant_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.identifiant_lineEdit.sizePolicy().hasHeightForWidth())
        self.identifiant_lineEdit.setSizePolicy(sizePolicy)
        self.identifiant_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.identifiant_lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.identifiant_lineEdit.setReadOnly(True)
        self.identifiant_lineEdit.setObjectName("identifiant_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.identifiant_lineEdit)
        self.nomEtPrNomLabel = QtWidgets.QLabel(self.layoutWidget)
        self.nomEtPrNomLabel.setObjectName("nomEtPrNomLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nomEtPrNomLabel)
        self.combo_nomP = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_nomP.setMinimumSize(QtCore.QSize(0, 40))
        self.combo_nomP.setMaximumSize(QtCore.QSize(16777215, 40))
        self.combo_nomP.setObjectName("combo_nomP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_nomP)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 220, 470, 52))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_submit = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_submit.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout.addWidget(self.btn_submit)
        self.btn_reset = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_reset.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout.addWidget(self.btn_reset)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Effacer un client"))
        self.label.setText(_translate("Dialog", "Effacer un client"))
        self.dSignationLabel.setText(_translate("Dialog", "Identifiant : "))
        self.nomEtPrNomLabel.setText(_translate("Dialog", "Nom et prénom : "))
        self.btn_submit.setText(_translate("Dialog", "Enregistrer"))
        self.btn_reset.setText(_translate("Dialog", "Annuler"))
