# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 620)
        Dialog.setMinimumSize(QtCore.QSize(850, 620))
        Dialog.setMaximumSize(QtCore.QSize(850, 620))
        Dialog.setAutoFillBackground(False)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(310, -20, 227, 91))
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 550, 841, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(537, 580, 301, 20))
        self.label_3.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_3.setObjectName("label_3")
        self.btn_nouvel_achat = QtWidgets.QPushButton(Dialog)
        self.btn_nouvel_achat.setGeometry(QtCore.QRect(108, 152, 250, 100))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_nouvel_achat.sizePolicy().hasHeightForWidth()
        )
        self.btn_nouvel_achat.setSizePolicy(sizePolicy)
        self.btn_nouvel_achat.setMinimumSize(QtCore.QSize(250, 100))
        self.btn_nouvel_achat.setMaximumSize(QtCore.QSize(250, 100))
        self.btn_nouvel_achat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nouvel_achat.setAutoFillBackground(False)
        self.btn_nouvel_achat.setAutoRepeat(False)
        self.btn_nouvel_achat.setAutoExclusive(False)
        self.btn_nouvel_achat.setFlat(False)
        self.btn_nouvel_achat.setObjectName("btn_nouvel_achat")
        self.btn_infos_clt = QtWidgets.QPushButton(Dialog)
        self.btn_infos_clt.setGeometry(QtCore.QRect(500, 150, 250, 100))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_infos_clt.sizePolicy().hasHeightForWidth()
        )
        self.btn_infos_clt.setSizePolicy(sizePolicy)
        self.btn_infos_clt.setMinimumSize(QtCore.QSize(250, 100))
        self.btn_infos_clt.setMaximumSize(QtCore.QSize(250, 100))
        self.btn_infos_clt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_infos_clt.setAutoFillBackground(False)
        self.btn_infos_clt.setAutoRepeat(False)
        self.btn_infos_clt.setAutoExclusive(False)
        self.btn_infos_clt.setFlat(False)
        self.btn_infos_clt.setObjectName("btn_infos_clt")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(340, 90, 165, 17))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_admin = QtWidgets.QPushButton(Dialog)
        self.btn_admin.setGeometry(QtCore.QRect(108, 360, 250, 100))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_admin.sizePolicy().hasHeightForWidth())
        self.btn_admin.setSizePolicy(sizePolicy)
        self.btn_admin.setMinimumSize(QtCore.QSize(250, 100))
        self.btn_admin.setMaximumSize(QtCore.QSize(250, 100))
        self.btn_admin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_admin.setAutoFillBackground(False)
        self.btn_admin.setAutoRepeat(False)
        self.btn_admin.setAutoExclusive(False)
        self.btn_admin.setFlat(False)
        self.btn_admin.setObjectName("btn_admin")
        self.btn_stock = QtWidgets.QPushButton(Dialog)
        self.btn_stock.setGeometry(QtCore.QRect(500, 360, 250, 100))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stock.sizePolicy().hasHeightForWidth())
        self.btn_stock.setSizePolicy(sizePolicy)
        self.btn_stock.setMinimumSize(QtCore.QSize(250, 100))
        self.btn_stock.setMaximumSize(QtCore.QSize(250, 100))
        self.btn_stock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_stock.setAutoFillBackground(False)
        self.btn_stock.setAutoRepeat(False)
        self.btn_stock.setAutoExclusive(False)
        self.btn_stock.setFlat(False)
        self.btn_stock.setObjectName("btn_stock")
        self.btn_apropos = QtWidgets.QPushButton(Dialog)
        self.btn_apropos.setGeometry(QtCore.QRect(10, 580, 221, 21))
        self.btn_apropos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_apropos.setFlat(True)
        self.btn_apropos.setObjectName("btn_apropos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Accueil Facturingo"))
        self.label.setText(_translate("Dialog", "\n" "Bienvenu sur Facturingo"))
        self.label_3.setText(
            _translate(
                "Dialog", "Facturingo V3.2.  Starland .inc Touts droits réservés"
            )
        )
        self.btn_nouvel_achat.setText(_translate("Dialog", "+\n" "Nouvel Achat\n" ""))
        self.btn_infos_clt.setText(
            _translate("Dialog", "\n" "Trouver les informations\n" "sur un client\n" "")
        )
        self.label_2.setText(_translate("Dialog", "Que voulez-vous faire ?"))
        self.btn_admin.setText(
            _translate(
                "Dialog", "\n" "Créer ou modifier\n" "Le compte administrateur\n" ""
            )
        )
        self.btn_stock.setText(_translate("Dialog", "\n" "Gestion du stock\n" ""))
        self.btn_apropos.setText(_translate("Dialog", "A propos de facturingo"))
