# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 695)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/img/F1-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.btn_modif = QtWidgets.QPushButton(self.centralwidget)
        self.btn_modif.setMinimumSize(QtCore.QSize(300, 100))
        self.btn_modif.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.btn_modif.setObjectName("btn_modif")
        self.gridLayout_2.addWidget(self.btn_modif, 3, 0, 1, 2)
        self.btn_stat = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stat.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_stat.setObjectName("btn_stat")
        self.gridLayout_2.addWidget(self.btn_stat, 3, 2, 1, 1)
        self.txt_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_log.setObjectName("txt_log")
        self.gridLayout_2.addWidget(self.txt_log, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(500, 673))
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing
        )
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.lb_photo = QtWidgets.QLabel(self.frame)
        self.lb_photo.setMinimumSize(QtCore.QSize(200, 200))
        self.lb_photo.setMaximumSize(QtCore.QSize(16777215, 200))
        self.lb_photo.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_photo.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
        )
        self.lb_photo.setObjectName("lb_photo")
        self.gridLayout.addWidget(self.lb_photo, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.nomLabel = QtWidgets.QLabel(self.groupBox)
        self.nomLabel.setObjectName("nomLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nomLabel)
        self.nomLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nomLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.nomLineEdit.setReadOnly(True)
        self.nomLineEdit.setObjectName("nomLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nomLineEdit)
        self.prNomLabel = QtWidgets.QLabel(self.groupBox)
        self.prNomLabel.setObjectName("prNomLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prNomLabel)
        self.prNomLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.prNomLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.prNomLineEdit.setReadOnly(True)
        self.prNomLineEdit.setObjectName("prNomLineEdit")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.prNomLineEdit
        )
        self.dateDeNaissanceLabel = QtWidgets.QLabel(self.groupBox)
        self.dateDeNaissanceLabel.setObjectName("dateDeNaissanceLabel")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.dateDeNaissanceLabel
        )
        self.dateDeNaissanceLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dateDeNaissanceLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.dateDeNaissanceLineEdit.setReadOnly(True)
        self.dateDeNaissanceLineEdit.setObjectName("dateDeNaissanceLineEdit")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.dateDeNaissanceLineEdit
        )
        self.loginLabel = QtWidgets.QLabel(self.groupBox)
        self.loginLabel.setObjectName("loginLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.loginLabel)
        self.loginLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.loginLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.loginLineEdit.setReadOnly(True)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.loginLineEdit
        )
        self.motDePasseLabel = QtWidgets.QLabel(self.groupBox)
        self.motDePasseLabel.setObjectName("motDePasseLabel")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.motDePasseLabel
        )
        self.motDePasseLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.motDePasseLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.motDePasseLineEdit.setReadOnly(True)
        self.motDePasseLineEdit.setObjectName("motDePasseLineEdit")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.motDePasseLineEdit
        )
        self.nDeTLPhoneLabel = QtWidgets.QLabel(self.groupBox)
        self.nDeTLPhoneLabel.setObjectName("nDeTLPhoneLabel")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.nDeTLPhoneLabel
        )
        self.nDeTLPhoneSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.nDeTLPhoneSpinBox.setMinimumSize(QtCore.QSize(0, 40))
        self.nDeTLPhoneSpinBox.setReadOnly(True)
        self.nDeTLPhoneSpinBox.setMaximum(999999999)
        self.nDeTLPhoneSpinBox.setObjectName("nDeTLPhoneSpinBox")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.FieldRole, self.nDeTLPhoneSpinBox
        )
        self.gridLayout_3.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Administration"))
        self.label_3.setText(
            _translate("MainWindow", "Problèmes durant ces derniers jours")
        )
        self.btn_modif.setText(
            _translate(
                "MainWindow",
                "\n" "Modifier les informations\n" "\n" "de administrateur\n" "",
            )
        )
        self.btn_stat.setText(_translate("MainWindow", "Statistiques des ventres"))
        self.txt_log.setPlainText(
            _translate("MainWindow", "Problèmes rencontrés ...\n" "")
        )
        self.dockWidget.setWindowTitle(_translate("MainWindow", "ADMINISTRATION"))
        self.label_2.setText(_translate("MainWindow", "Landry Simo"))
        self.lb_photo.setText(_translate("MainWindow", "Photo de l'admin"))
        self.groupBox.setTitle(_translate("MainWindow", "Détails :"))
        self.nomLabel.setText(_translate("MainWindow", "Nom : "))
        self.prNomLabel.setText(_translate("MainWindow", "Prénom : "))
        self.dateDeNaissanceLabel.setText(
            _translate("MainWindow", "Date de naissance : ")
        )
        self.loginLabel.setText(_translate("MainWindow", "login : "))
        self.motDePasseLabel.setText(_translate("MainWindow", "Mot de passe : "))
        self.nDeTLPhoneLabel.setText(_translate("MainWindow", "N° de téléphone : "))
